### ISSUE TITLE
Input Data with numeric digits

### ISSUE THREAD

**Issue by cnguyen123** [cnguyen123/piglatinWASP#4]
How to manage input data combined between numerics and characters, for example : hello123world

**Comment by cnguyen123** [comment]
And data input with some special characters: punctuation, currency sign, etc??

**Comment by jiexiong2016** [comment]
Will add some special character check for preventing this condition since it doesn't make sense to translate number or these characters.

**Comment by jiexiong2016** [comment]
Fixed, added a function "isAlpha" to perform the function
